/*
 * 1. Ensure you have run the updated 'train_model.py' script.
 * 2. Put the generated 'model_data.h' in the same folder as this .ino file.
 * 3. NO EXTERNAL ML LIBRARIES NEEDED ANYMORE! (Removed EloquentTinyML)
 * 4. Open this file in the Arduino IDE and flash it to your ESP32-S3.
 */

#include <Arduino.h>
#include <Wire.h>
#include <WiFi.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>
#include "DFRobot_C4001.h"

// Include the purely converted C++ Random Forest model
#include "model_data.h" 

// Instantiate the Random Forest model class generated by micromlgen
Eloquent::ML::Port::RandomForestModel rf_model;

// ---------------- WIFI SETTINGS ----------------
const char* WIFI_SSID = "YASWANTH 8448"; 
const char* WIFI_PASS = "Yaswanth@2407";
const uint32_t WIFI_CONNECT_TIMEOUT_MS = 20000; 
bool wifiOK = false;

// ---------------- TIME & NTP SETTINGS ----------------
const long GMT_OFFSET_SEC = 19800; // IST is UTC+5:30 (5.5 * 3600)
const int DAYLIGHT_OFFSET_SEC = 0;
const uint32_t TIME_SYNC_TIMEOUT_MS = 10000;
const uint32_t WIFI_RETRY_MS = 30000;
const uint32_t TIME_RETRY_MS = 60000;
bool timeOK = false;

// ---------------- PIN SETTINGS ----------------
#define C4001_SDA 6
#define C4001_SCL 7

#define OLED_SDA 8
#define OLED_SCL 9
#define OLED_ADDR 0x3C

#define RD03D_RX_PIN 4
#define RD03D_TX_PIN 5
#define RD03D_BAUD 256000

#define C4001_DETECT_THRESHOLD 200

// ---------------- HARDWARE OBJECTS ----------------
HardwareSerial rdSerial(1);
DFRobot_C4001_I2C c4001;
Adafruit_SH1106G display = Adafruit_SH1106G(128, 64, &Wire1, -1);

// ---------------- GLOBAL SENSOR VARIABLES ----------------
float rd_present = 0.0; 
float rd_distance_mm = 0.0;
float rd_velocity_cm_s = 0.0;
float rd_angle_deg = 0.0;
float rd_x_mm = 0.0;
float rd_y_mm = 0.0;

float c4001_present = 0.0; 
float c4001_distance_m = 0.0; 
float c4001_velocity_m_s = 0.0; 
float c4001_energy = 0.0;
float c4001_raw_targets = 0.0;
float c4001_raw_distance_m = 0.0;
float c4001_raw_velocity_m_s = 0.0;
float c4001_raw_energy = 0.0;

// Timer for non-blocking ML inference
unsigned long lastInferenceTime = 0;
const unsigned long INFERENCE_INTERVAL = 500; 

// ---------------- SENSOR DATA SMOOTHING BUFFER ----------------
#define SENSOR_SMOOTHING_WINDOW 5
float sensorHistory[10][SENSOR_SMOOTHING_WINDOW]; // 10 features, window size 5
uint8_t sensorHistIndex = 0;
bool sensorHistFilled = false; // Flag to indicate if buffer is full

// ---------------- PREDICTION SMOOTHING BUFFER & ACCURACY ----------------
#define SMOOTHING_WINDOW 5
String predictionHistory[SMOOTHING_WINDOW];
uint8_t predIndex = 0;

// Function to get smoothed prediction AND calculate live confidence (accuracy)
String getSmoothedPrediction(String new_pred, int &out_confidence) {
    predictionHistory[predIndex] = new_pred;
    predIndex = (predIndex + 1) % SMOOTHING_WINDOW;
    
    int max_count = 0;
    String best_pred = new_pred;
    
    for (int i = 0; i < SMOOTHING_WINDOW; i++) {
        if (predictionHistory[i].length() == 0) continue;
        int count = 0;
        for (int j = 0; j < SMOOTHING_WINDOW; j++) {
            if (predictionHistory[i] == predictionHistory[j]) count++;
        }
        if (count > max_count) {
            max_count = count;
            best_pred = predictionHistory[i];
        }
    }
    
    // Calculate Live Accuracy/Confidence percentage based on stability
    out_confidence = (max_count * 100) / SMOOTHING_WINDOW;
    
    return best_pred;
}

// ---------------- WIFI & TIME CONNECTION LOGIC ----------------
String getDateTimeString() {
  struct tm timeinfo;
  if (!getLocalTime(&timeinfo, 200)) { return "TIME_NOT_SYNCED"; }
  char buf[24];
  strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &timeinfo);
  return String(buf);
}

bool isTimeValid() {
  struct tm timeinfo;
  if (!getLocalTime(&timeinfo, 100)) return false;
  int year = timeinfo.tm_year + 1900;
  return year >= 2024;
}

bool waitForTimeSync(uint32_t timeoutMs) {
  uint32_t start = millis();
  while (millis() - start < timeoutMs) {
    if (isTimeValid()) return true;
    delay(250);
  }
  return false;
}

bool connectWiFi() {
  if (WiFi.status() == WL_CONNECTED) { wifiOK = true; return true; }
  Serial.println("Connecting WiFi...");
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t start = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - start < WIFI_CONNECT_TIMEOUT_MS) { delay(250); }
  if (WiFi.status() == WL_CONNECTED) { wifiOK = true; return true; }
  wifiOK = false;
  return false;
}

bool syncDateTime() {
  if (!connectWiFi()) return false;
  configTime(GMT_OFFSET_SEC, DAYLIGHT_OFFSET_SEC, "pool.ntp.org", "time.google.com", "time.nist.gov");
  timeOK = waitForTimeSync(TIME_SYNC_TIMEOUT_MS);
  return timeOK;
}

void maintainWiFiAndTime() {
  static uint32_t lastWifiTry = 0;
  static uint32_t lastTimeTry = 0;
  uint32_t nowMs = millis();
  if (WiFi.status() != WL_CONNECTED) {
    wifiOK = false; timeOK = false;
    if (nowMs - lastWifiTry >= WIFI_RETRY_MS) { lastWifiTry = nowMs; connectWiFi(); }
    return;
  }
  wifiOK = true;
  if (isTimeValid()) { timeOK = true; return; }
  timeOK = false;
  if (nowMs - lastTimeTry >= TIME_RETRY_MS) { lastTimeTry = nowMs; syncDateTime(); }
}

void setup() {
    Serial.begin(115200);
    while (!Serial); 
    
    Serial.println("ESP32-S3 Random Forest Real-Time Inference Started!");
    Serial.println("-------------------------------------------------");

    // --- CONNECT WIFI ---
    connectWiFi();
    syncDateTime();

    // --- INIT RD-03D RADAR ---
    rdSerial.begin(RD03D_BAUD, SERIAL_8N1, RD03D_RX_PIN, RD03D_TX_PIN);
    Serial.println("RD-03D UART initialized.");

    // --- INIT C4001 RADAR ---
    Wire.begin(C4001_SDA, C4001_SCL);
    while (!c4001.begin()) {
      Serial.println("C4001 not found on SDA 6 / SCL 7.");
      delay(500);
    }
    Serial.println("C4001 connected.");
    
    c4001.setSensorMode(eSpeedMode);
    c4001.setDetectThres(40, 400, C4001_DETECT_THRESHOLD);
    c4001.setFrettingDetection(eOFF);

    // --- INIT OLED DISPLAY ---
    Wire1.begin(OLED_SDA, OLED_SCL);
    if (!display.begin(OLED_ADDR, true)) {
        Serial.println("OLED connection failed!");
    } else {
        Serial.println("OLED connected.");
        display.clearDisplay();
        display.setTextSize(1);
        display.setTextColor(SH110X_WHITE);
        display.setCursor(0, 10);
        display.println("ML System Ready");
        
        display.setCursor(0, 25);
        if(wifiOK) display.println("WiFi: Connected");
        else display.println("WiFi: Failed");
        
        display.display();
    }

    // Initialize prediction history buffer
    for(int i = 0; i < SMOOTHING_WINDOW; i++) {
        predictionHistory[i] = "";
    }
    
    // Initialize sensor history buffer
    for(int i = 0; i < 10; i++) {
        for(int j = 0; j < SENSOR_SMOOTHING_WINDOW; j++) {
            sensorHistory[i][j] = 0.0;
        }
    }
}

void loop() {
    maintainWiFiAndTime();

    // ==============================================================
    // 1. CONTINUOUS SENSOR READING (Non-Blocking)
    // ==============================================================
    
    // ---> RD-03D SERIAL PARSING LOGIC <---
    while (rdSerial.available()) {
        uint8_t b = rdSerial.read();
        static uint8_t rdBuf[30];
        static uint8_t rdPos = 0;
        const uint8_t RD_HEADER[4] = {0xAA, 0xFF, 0x03, 0x00};
        const uint8_t RD_FOOTER[2] = {0x55, 0xCC};

        if (rdPos < 4) {
            if (b == RD_HEADER[rdPos]) { rdBuf[rdPos++] = b; } 
            else if (b == RD_HEADER[0]) { rdBuf[0] = b; rdPos = 1; } 
            else { rdPos = 0; }
            continue;
        }

        rdBuf[rdPos++] = b;

        if (rdPos >= 30) {
            if (rdBuf[28] == RD_FOOTER[0] && rdBuf[29] == RD_FOOTER[1]) {
                int16_t x = ((rdBuf[5] & 0x7F) << 8) | rdBuf[4];
                if ((rdBuf[5] & 0x80) == 0) x = -x;

                int16_t y = ((rdBuf[7] & 0x7F) << 8) | rdBuf[6];
                if ((rdBuf[7] & 0x80) == 0) y = -y;

                int16_t speed = ((rdBuf[9] & 0x7F) << 8) | rdBuf[8];
                if ((rdBuf[9] & 0x80) == 0) speed = -speed;

                uint16_t res = ((uint16_t)rdBuf[11] << 8) | rdBuf[10];

                bool present = (x != 0 || y != 0 || res != 0);

                rd_present = present ? 1.0 : 0.0;
                rd_x_mm = (float)x;
                rd_y_mm = (float)y;
                rd_velocity_cm_s = (float)speed;
                rd_distance_mm = sqrt((float)x * x + (float)y * y);
                rd_angle_deg = atan2((float)x, (float)y) * 180.0 / PI;
            }
            rdPos = 0;
        }
    }

    // ---> C4001 I2C READING LOGIC <---
    uint16_t targetCount = c4001.getTargetNumber();
    c4001_raw_targets = (float)targetCount;

    if (targetCount > 0) {
        c4001_present = 1.0; 
        c4001_distance_m = c4001.getTargetRange();
        c4001_velocity_m_s = c4001.getTargetSpeed();
        c4001_energy = (float)c4001.getTargetEnergy();
        
        c4001_raw_distance_m = c4001_distance_m;
        c4001_raw_velocity_m_s = c4001_velocity_m_s;
        c4001_raw_energy = c4001_energy;
    } else {
        c4001_present = 0.0;
        c4001_distance_m = 0.0;
        c4001_velocity_m_s = 0.0;
        c4001_energy = 0.0;
        c4001_raw_distance_m = 0.0;
        c4001_raw_velocity_m_s = 0.0;
        c4001_raw_energy = 0.0;
    }

    // ==============================================================
    // 2. TIMED INFERENCE ENGINE (Runs every 500ms)
    // ==============================================================
    unsigned long currentMillis = millis();
    
    if (currentMillis - lastInferenceTime >= INFERENCE_INTERVAL) {
        lastInferenceTime = currentMillis;

        // Calculate combined features
        float combined_rd_angle_deg_rd_x_mm = (rd_angle_deg + rd_x_mm) / 2.0;
        float combined_rd_distance_mm_rd_y_mm = (rd_distance_mm + rd_y_mm) / 2.0;
        float combined_c4001_velocity_m_s_c4001_raw_velocity_m_s = (c4001_velocity_m_s + c4001_raw_velocity_m_s) / 2.0;
        float combined_c4001_energy_c4001_raw_energy = (c4001_energy + c4001_raw_energy) / 2.0;

        // --------------------------------------------------------------------------
        // STRICT ALPHABETICAL ORDER ARRAY (Matching Python Training Order)
        // --------------------------------------------------------------------------
        float instantaneous_data[10] = {
            c4001_distance_m,                                   // Index 0
            c4001_present,                                      // Index 1
            c4001_raw_distance_m,                               // Index 2
            c4001_raw_targets,                                  // Index 3
            combined_c4001_energy_c4001_raw_energy,             // Index 4
            combined_c4001_velocity_m_s_c4001_raw_velocity_m_s, // Index 5
            combined_rd_angle_deg_rd_x_mm,                      // Index 6
            combined_rd_distance_mm_rd_y_mm,                    // Index 7
            rd_present,                                         // Index 8
            rd_velocity_cm_s                                    // Index 9
        };

        // Add instantaneous values to rolling buffer
        for(int i=0; i<10; i++) {
             sensorHistory[i][sensorHistIndex] = instantaneous_data[i];
        }
        sensorHistIndex++;
        if (sensorHistIndex >= SENSOR_SMOOTHING_WINDOW) {
            sensorHistIndex = 0;
            sensorHistFilled = true; // Buffer is full, we can calculate meaningful averages
        }

        // Calculate the rolling mean for each feature
        float smoothed_sensor_data[10];
        for(int i=0; i<10; i++) {
             float sum = 0.0;
             // If buffer not full, average only over collected samples to prevent dividing by 0s
             int count = sensorHistFilled ? SENSOR_SMOOTHING_WINDOW : sensorHistIndex; 
             if(count == 0) count = 1; 
             
             for(int j=0; j<count; j++){
                 sum += sensorHistory[i][j];
             }
             smoothed_sensor_data[i] = sum / count;
        }

        // --- RUN RANDOM FOREST PREDICTION USING SMOOTHED DATA ---
        int predicted_index = rf_model.predict(smoothed_sensor_data);
        String raw_prediction = String(class_activitys[predicted_index]);
        
        // ==============================================================
        // GHOST TARGET FILTER
        // Overrides AI if the room is empty (No C4001 micro-motion + 0 RD-03D speed)
        // ==============================================================
        if (c4001_raw_targets == 0.0 && rd_velocity_cm_s == 0.0) {
             raw_prediction = "NO_PERSON";
        }
        
        // Calculate smoothed prediction and Live Confidence Accuracy
        int live_accuracy = 0;
        String predicted_action = getSmoothedPrediction(raw_prediction, live_accuracy);
        
        Serial.print("🌲 Raw: ");
        Serial.print(raw_prediction);
        Serial.print("  |  🎯 Output: ");
        Serial.print(predicted_action);
        Serial.print("  |  Confidence: ");
        Serial.print(live_accuracy);
        Serial.println("%");

        // --- UPDATE OLED SCREEN ---
        display.clearDisplay();
        
        // 1. Display the Prediction & Accuracy at the top
        display.setTextSize(1);
        display.setCursor(0, 0);
        display.print(predicted_action);
        
        // Print accuracy on the right side
        display.setCursor(90, 0);
        display.print(live_accuracy);
        display.print("%");
        
        // 2. Display Human-Readable Sensors
        display.setCursor(0, 14); display.print("RV:"); display.print(rd_velocity_cm_s, 0); 
        display.setCursor(64, 14); display.print("C4D:"); display.print(c4001_distance_m, 2);
        
        display.setCursor(0, 24); display.print("RD:"); display.print(rd_distance_mm, 0);
        display.setCursor(64, 24); display.print("C4V:"); display.print(c4001_velocity_m_s, 2);
        
        display.setCursor(0, 34); display.print("RA:"); display.print(rd_angle_deg, 0);
        display.setCursor(64, 34); display.print("Tgt:"); display.print(c4001_raw_targets, 0);
        
        display.setCursor(0, 44); display.print("RX:"); display.print(rd_x_mm, 0);
        display.setCursor(0, 54); display.print("RY:"); display.print(rd_y_mm, 0);
        
        display.display();
    }
}